name: Build

on:
  push:
    branches: 
      - master

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04
    env: 
      VERSION: master
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        cd $HOME
        sudo apt update
        sudo apt install lsb-release libatk1.0-0 libcairo-gobject2 libcairo2 libdbus-1-3 libdbus-glib-1-2 libfontconfig1 libfreetype6 libgcc1 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libpango-1.0-0 libpangocairo-1.0-0 libstartup-notification0 libstdc++6 libx11-6 libx11-xcb1 libxcb-shm0 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrender1 libxt6 -y
    - name: Build
      run: |
        ./build
        sudo ./build install
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: firefoxdev_amd64.deb
        path: /root/firefoxdev_amd64.deb
